# 配置Spring数据源
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  profiles:
    include: dev

  cloud:
    nacos:
      discovery:
        server-addr: ${moyan.nacos.discovery.server-addr}
        username: ${moyan.nacos.discovery.username}
        password: ${moyan.nacos.discovery.password}
        group: ${moyan.nacos.discovery.group}
        namespace: ${moyan.nacos.discovery.namespace}
    loadbalancer:
      enabled: true
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
#            allowedOrigins: "*"
            allowed-origin-patterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
        add-to-simple-url-handler-mapping: true

      routes:
        - id: service-user1
          uri: lb://service-user
          predicates:
            - Path=/user/**
        - id: service-user2
          uri: lb://service-user
          predicates:
            - Path=/user-info/**
        - id: service-user3
          uri: lb://service-user
          predicates:
            - Path=/search/**
        - id: service-user4
          uri: lb://service-user
          predicates:
            - Path=/member/**
        - id: service-user5
          uri: lb://service-user
          predicates:
            - Path=/member-work/**
        - id: service-user6
          uri: lb://service-user
          predicates:
            - Path=/member-info/**
        - id: service-user7
          uri: lb://service-user
          predicates:
            - Path=/admin/**
        - id: service-user8
          uri: lb://service-user
          predicates:
            - Path=/admin-manage/**
        - id: service-user9
          uri: lb://service-user
          predicates:
            - Path=/test/**


moyanshushe:
  jwt:
    # 用户接口JWT签名密钥
    secret-key: ${moyan.jwt.user-secret-key}
    # 用户接口JWT有效期
    ttl: ${moyan.jwt.user-ttl}
    # 用户接口请求头中JWT的字段名
    token-name: ${moyan.jwt.user-token-name}
    member-check: true
    user-check: true


  auth:
    exclude:
      exclude-paths:
        - /user/login
        - /search/**
        - /user/register
        - /admin/register
        - /user/verify
        - /admin/verify
        - /test/**
        - /user/openapi.html
server:
  port: 19500

